export const environment = {
  production: true,
  serverhost: "https://serveritclabs.itclabs.com/rest/",
  // serverhost: "https://uatserveritclabs.e-labs.ai/rest/",
  // serverhost: "https://serveraal.allaboutlab.com/rest/",
  // serverhost: "https://serverqualiteklab.e-labs.ai/rest/",
  // serverhost: "https://uatserverqualiteklab.e-labs.ai/rest/",
  // serverhost: "https://sitserverelabs.e-labs.ai/rest/",
  // serverhost: "https://serverhardgoodlabs.e-labs.ai/rest/",
  mediceaHost: "http://pcp.medicea.in/rest/",
  appId: "com.itcuat.ai",
  appName: "ITC Uat",
  appPlatformName: "itc-uat",
  web_site: "ITC Uat",
  razorpay_key : "rzp_test_P7SL8C2oelMvzE",
  verify_type : "email",
  app_Version : "@2022 ITC Uat v0.0.1",
  privacy_policy: "",
  app_share: "https://play.google.com/store/apps/details?id=com.itcuat.ai"
};
